version: '3.9'

services:
  postgres:
    container_name: postgres-url-shortener
    image: postgres:16.3-alpine
    networks:
      - network
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  network:

volumes:
  postgres_data: